name: CI
on: [push]
jobs:
  test_build_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: docker login -u $DOCKER_USER -p  $DOCKER_PASSWORD
      - name: Run tests
        run: |
          pip install pytest
          pytest
