name: CI
on: [push]
jobs:
  test_build_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pip install pytest
          pytest
